sei-protocol/sei-cosmwasm

packages/sei-cosmwasm/src/query.rs
Callers would need to access the fields in the response
=> Make response struct fields public

contracts/sei-tester/src/contract.rs, contracts/sei-tester/src/msg.rs, packages/sei-cosmwasm/src/lib.rs, packages/sei-cosmwasm/src/proto_structs.rs, packages/sei-cosmwasm/src/querier.rs, packages/sei-cosmwasm/src/query.rs, packages/sei-cosmwasm/src/route.rs
Still working on testing, but this introduces get epoch functionality into the sei-cosmwasm package
=> [epoch] Add get epoch and fix get dex twaps

packages/sei-cosmwasm/src/proto_structs.rs
=> Fix dex twap field name

contracts/sei-tester/src/contract.rs, contracts/sei-tester/src/msg.rs, packages/sei-cosmwasm/src/lib.rs, packages/sei-cosmwasm/src/querier.rs, packages/sei-cosmwasm/src/query.rs
This PR adds the query_order_simulation msg into sei-cosmwasm package.
=> Add check liquidity query

contracts/sei-tester/src/contract.rs, contracts/sei-tester/src/lib.rs, contracts/sei-tester/src/types.rs, packages/sei-cosmwasm/src/sei_types.rs
Add order data example to sei-tester
=> Add orderdata example

contracts/sei-tester/src/contract.rs, packages/sei-cosmwasm/src/lib.rs, packages/sei-cosmwasm/src/sei_types.rs
- Adds a reply handler to parse the sei-chain place order response for the order Ids
=> Add reply handler for place orders

contracts/sei-tester/src/contract.rs, contracts/sei-tester/src/msg.rs, packages/sei-cosmwasm/src/lib.rs, packages/sei-cosmwasm/src/querier.rs, packages/sei-cosmwasm/src/query.rs, packages/sei-cosmwasm/src/route.rs
- Adds tokenfactory queries to whitelist to sei-cosmwasm
=> Add tokenfactory queries

contracts/sei-tester/deployment/deployment_script.sh, contracts/sei-tester/src/contract.rs, packages/sei-cosmwasm/Cargo.toml, packages/sei-cosmwasm/README.md
This PR updates the tokenfactory example and readme
=> Update tokenfactory examples and README

tests/common/mod.rs, tests/sei_cosmwasm_integration_tests.rs
Adds integration test functionality for placing and querying orders
=> add dex module foundation for integration tests

contracts/sei-tester/deployment/deployment_script.sh, contracts/sei-tester/src/contract.rs, packages/sei-cosmwasm/Cargo.toml, packages/sei-cosmwasm/README.md, packages/sei-cosmwasm/src/sei_types.rs
More details can be found in this PR: https://github.com/sei-protocol/sei-chain/pull/295
=> Add market order by nominal type

contracts/sei-tester/src/contract.rs, tests/common/mod.rs, tests/sei_cosmwasm_integration_tests.rs
-Add epoch module functionality (not SudoMsg update for now since issues updating epoch within SeiModule)
-SudoMsg are empty handlers for now (not external user facing)
=> add epoch and sudo setup

packages/sei-cosmwasm/Cargo.toml
- Create new version for sei-cosmwasm
=> Bump sei cosmwasm version to 0.4.8

packages/sei-cosmwasm/README.md
- Updates readme to version 0.4.8
=> Update readme for version 0.4.8

contracts/sei-tester/src/contract.rs, contracts/sei-tester/src/msg.rs, contracts/sei-tester/tests/sei_tester_integration_tests.rs, packages/sei-cosmwasm/src/lib.rs, packages/sei-cosmwasm/src/querier.rs, packages/sei-cosmwasm/src/query.rs, packages/sei-integration-tests/src/module.rs
- Removes the denom creation fee whitelist and associated messages from sei-cosmwasm
- Verified with sei-tester that it is removed
=> Remove denom creation fee whitelist from sei-cosmwasm

packages/sei-cosmwasm/Cargo.toml
```
Compiling sei-cosmwasm v0.4.9 (/Users/brandon/sei/sei-cosmwasm/target/package/sei-cosmwasm-0.4.9)
Finished dev [unoptimized + debuginfo] target(s) in 13.12s
Uploading sei-cosmwasm v0.4.9 (/Users/brandon/sei/sei-cosmwasm/packages/sei-cosmwasm)
```
=> Bump cargo toml

packages/sei-cosmwasm/Cargo.toml, packages/sei-cosmwasm/README.md, packages/sei-integration-tests/Cargo.toml
Bumps version of sei-cosmwasm and sei-integration-test to 0.4.10
Will publish new crate version
=> Bump package versions to 0.4.10

.github/workflows/Basic.yml, README.md, packages/sei-cosmwasm/Cargo.toml, packages/sei-cosmwasm/src/proto_structs.rs
This updates the type for exchange rates queried from the oracle module to include the new field "last_update_timestamp" that is going to be introduced in the newest upgrade
=> add last update timestamp to oracle exchage rate struct

.github/ISSUE_TEMPLATE/bug_report.md
This will encourage users to fill in a template with useful information for us to help them.
=> add issue template dir and template for bug report

README.md, contracts/sei-tester/src/contract.rs, contracts/sei-tester/src/lib.rs, contracts/sei-tester/src/msg.rs, contracts/sei-tester/src/state.rs
Add some helper functions for testing iterators and parallel access
=> Add functionality for iterator and parallel access for loadtesting

contracts/sei-tester/src/contract.rs
This adds functions to test concurrent workloads as well as iteration heavy workloads
=> Add sei tester functionality for iterator heavy workloads

packages/sei-integration-tests/Cargo.toml
Update version of sei-integration-tests
=> Update version of sei-integration-tests
